pipeline{
    agent any
    stages {
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }
        stage('Deploy'){
            steps{
                echo "Simulando un despliegue a un servidor"
            }
        }
    }
    post{
        always{
            echo "Siempre se ejecuta"
        }
        success{
            echo "Exito"
        }
        failure{
            echo "Fallo"
        }
    }
}